INSERT INTO Usuario (email, password, rol, activo, nombre)
SELECT 'test@unlam.edu.ar', 'test', 'ADMIN', true, 'Administrador'
WHERE NOT EXISTS (
        SELECT email FROM Usuario WHERE email = 'test@unlam.edu.ar'
    ) LIMIT 1;


INSERT INTO marca (id, nombre) VALUES ('1', 'Chevrolet');
INSERT INTO marca (id, nombre) VALUES ('2', 'Ford');
INSERT INTO marca (id, nombre) VALUES ('3', 'Volkswagen');
INSERT INTO marca (id, nombre) VALUES ('4', 'Renault');
INSERT INTO marca (id, nombre) VALUES ('5', 'Fiat');
INSERT INTO marca (id, nombre) VALUES ('6', 'Toyota');
INSERT INTO marca (id, nombre) VALUES ('7', 'Peugeot');
INSERT INTO marca (id, nombre) VALUES ('8', 'Honda');
INSERT INTO marca (id, nombre) VALUES ('9', 'Nissan');
INSERT INTO marca (id, nombre) VALUES ('10', 'Citroën');
INSERT INTO marca (id, nombre) VALUES ('11', 'Hyundai');
INSERT INTO marca (id, nombre) VALUES ('12', 'Kia');
INSERT INTO marca (id, nombre) VALUES ('13', 'Mazda');
INSERT INTO marca (id, nombre) VALUES ('14', 'Nissan');
INSERT INTO marca (id, nombre) VALUES ('15', 'Audi');
INSERT INTO marca (id, nombre) VALUES ('16', 'BMW');
INSERT INTO marca (id, nombre) VALUES ('17', 'Mercedes-Benz');
INSERT INTO marca (id, nombre) VALUES ('18', 'Renault');
INSERT INTO marca (id, nombre) VALUES ('19', 'Fiat');
INSERT INTO marca (id, nombre) VALUES ('20', 'SEAT');

INSERT INTO modelo (id, nombre, id_marca) VALUES ('101', 'Corsa', '1');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('102', 'Cruze', '1');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('103', 'Onix', '1');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('104', 'Tracker', '1');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('201', 'Fiesta', '2');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('202', 'Focus', '2');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('203', 'Mustang', '2');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('204', 'Ranger', '2');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('301', 'Gol', '3');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('302', 'Polo', '3');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('303', 'Tiguan', '3');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('304', 'Vento', '3');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('401', 'Clio', '4');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('402', 'Duster', '4');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('403', 'Fluence', '4');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('404', 'Sandero', '4');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('501', 'Palio', '5');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('502', 'Siena', '5');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('503', 'Strada', '5');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('504', 'Uno', '5');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('601', 'Corolla', '6');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('602', 'Hilux', '6');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('603', 'RAV4', '6');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('604', 'Yaris', '6');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('701', '208', '7');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('702', '308', '7');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('703', '408', '7');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('704', 'Partner', '7');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('801', 'Civic', '8');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('802', 'CR-V', '8');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('803', 'Fit', '8');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('804', 'HR-V', '8');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('901', 'March', '9');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('902', 'Sentra', '9');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('903', 'Versa', '9');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('904', 'X-Trail', '9');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1001', 'C3', '10');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1002', 'C4', '10');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1003', 'C-Elysée', '10');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1004', 'C4 Cactus', '10');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1101', 'Polo', '11');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1102', 'Sonata', '11');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1103', 'Elantra', '11');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1104', 'Tucson', '11');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1201', 'Picanto', '12');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1202', 'Rio', '12');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1203', 'Seltos', '12');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1204', 'Sportage', '12');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1301', '3', '13');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1302', '6', '13');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1303', 'CX-3', '13');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1304', 'CX-5', '13');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1401', 'Qashqai', '14');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1402', 'Juke', '14');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1403', 'Micra', '14');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1404', 'Leaf', '14');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1501', 'A1', '15');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1502', 'A3', '15');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1503', 'A4', '15');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1504', 'Q3', '15');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1601', 'Serie 1', '16');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1602', 'Serie 2', '16');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1603', 'Serie 3', '16');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1604', 'X1', '16');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1701', 'Clase A', '17');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1702', 'Clase C', '17');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1703', 'Clase E', '17');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1704', 'GLA', '17');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1801', 'Clio', '18');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1802', 'Megane', '18');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1803', 'Kadjar', '18');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1804', 'Koleos', '18');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1901', '500', '19');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1902', 'Panda', '19');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1903', 'Tipo', '19');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('1904', '500X', '19');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('2001', 'Leon', '20');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('2002', 'Ibiza', '20');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('2003', 'Arona', '20');
INSERT INTO modelo (id, nombre, id_marca) VALUES ('2004', 'Ateca', '20');
