-- Inserción condicional de usuario
INSERT INTO Usuario (email, password, rol, activo, nombre)
SELECT 'test@unlam.edu.ar', 'test', 'ADMIN', true, 'Administrador'
    WHERE NOT EXISTS (
        SELECT 1 FROM Usuario WHERE email = 'test@unlam.edu.ar'
    ) LIMIT 1;
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 1,'La recomendación para este caso es verificar el funcionamiento de las mangueras de gasolina, en caso de que estas esten bien puede ser el tanque que este roto.' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 1);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 2,'Para el auto, si tienes las herramientas suficientes remplaza la manguera' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 2);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 3,'En este caso lo mejor seria cambiar este componente y verificar si ningun otro componente se encuentra dañado como la rosca de la sondo de grasa' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 3);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 4,'En este caso el auto podria arreglarse apagando el auto un tiempo pero pronto volvera a perder potencia, lo recomendable es cambiar el catalizador' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 4);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 5,'En el caso de que las bujias se encuentras color crema y estan limpias y secas significa que estan en buen estado, de lo contrario estaria averiadas lo cual es recomendable cambiarlas' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 5);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 6,'Lo mejor seria cambiar esta tapa para evitar la fuga' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 6);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 7,'Aunque con una buena limpieza de esta pieza puede seguir andando lo recomendables es cambiarla' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 7);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 8,'Cambiar estas bobinas para un mejor funcionamiento del auto' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 8);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 9,'Este es imposible de reparar, asi que hay que sustituirlo por uno nuevo' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 9);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 10,'desarmar el dispositivo, extraer la tarjeta integrada y desempolvarla con un limpiador de dispositivos electrónicos. ' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 10);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 11,'Este es imposible de reparar, asi que hay que sustituirlo por uno nuevo' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 11);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 12,'Cambiar estos cables para un correcto funcionamiento' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 12);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 13,'Esto puede estropear el auto asi que es recomendable cambiarlo rapidamente' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 13);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 14,'Cambiar las mangueras' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 14);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 15,'Instalar adecuadamente o consultar con un profesional' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 15);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 16,'Esto puede deberse a diferentes cosas se recomienda visitar un profesional' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 16);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 17,'Sustituir este liquido por uno nuevo para evitar la contaminación' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 17);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 18,'Cambiar por neumaticos mas nuevos' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 18);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 19,'Para evitar incidentes cambiar urgente' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 19);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 20,'Limpiar la zona de forma muy prolija para que este filtro pueda funcionar o cambiar la pieza' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 20);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 21,'Lo recomendable es que cambies este filtro ya que se va a encontrar dañado a causa de el mal combustible' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 21);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 22,'Realizar el mantenimiento diariamente para evitar que se dañen otras zonas' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 22);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 23,'Cambiar inmediatamente la pieza' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 23);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 24,'Cambiar o limpiar la pieza para un mejor funcionamiento' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 24);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 25,'En este caso lo mejor seria cambiar los muelles o verificar si las ruedas del auto estan desbalanceadas' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 25);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 26,'Cambiar los amortiguadores o tambien podria ser el muelle pero en gran parte esto esta afectado a los amortiguadores' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 26);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 27,'Lo mejor es sustituir los neumaticos que estan en mal estado y alinearlos en el taller' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 27);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 28,'En este caso es posible que esten perdiendo liquido, lo mas recomendable es llevarlo al taller para saber de donde pierde' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 28);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 29,'En el caso de qu esten sucios limpiarlos suavemente para no dañar el dispositivo con un trapo poco humedo, si esto no soluciona hay que cambiar la pieza.' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 29);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 30,'Cambiar el airbag ya que esta pieza al estar mojada no sirve mas' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 30);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 31,'Cambiar la pieza del reloj, lo recomendable es que lo haga un profesional para que no dañe el airbag' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 31);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 32,'Llevar a un electricista para comprobar el correcto funcionamiento, el profesional te diagnosticara si ese es el problema' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 32);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 33,'Cambiar el airbag' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 33);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 34,'Para poder solucionarlo deberias levantar despacio el pie del acelerador y hacer una maniobra de contravolante.' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 34);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 35,'En primer caso inflar los neumaticos a la presion correcta, sino hay que ajustar la banda o revisar la alineacion delantera' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 35);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 36,'Ajustar la presion de los neumaticos, sino puede ser los amortiguadores o rotulas dañados, si estan dañados cambiarlos inmediatamente' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 36);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 37,'La barra de acoplamiento se ha desgastado, lo que provoca que se suelte y se desarrolla un juego excesivo, cambiar esta pieza' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 37);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 38,'Ajustar la presion de los neumaticos, sino cambiar las ruedas pueden estar muy dañadas y alinearlas' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 38);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 39,'Los posibles culpables de esto van a ser las articulaciones y rotulas de la suspension rota o desgastada' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 39);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 40,'Esto sucede cuando esta muy desgastado o roto entonces hay que cambiar esta pieza' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 40);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 41,'Imposible el uso del auto cambiar la pieza inmediatamente' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 41);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 42,'Cambiar la pieza del bombin ya que este dificulta el andar del auto' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 42);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 43,'Su vida util llego al final hay que cambiar esta pieza' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 43);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 44,'Utilizaremos un liquido de limpieza como por ejemplo Eclipse,  que nos ayudara con la limpieza de este sector' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 44);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 45,'Esto indica que el sistema esta perdiendo traccion pero que el esp esta funcionando, se recomienda llevarlo al taller' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 45);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 46,'Esto puede ocurrir por la acumulacion de suciedad en los componentes, se recomienda hacer movimientos suaves del volante para la situacion se reconduzca' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 46);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 47,'Llevar a un taller de inmediato' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 47);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 48,'Si no arranca el auto es posible que la bateria este fallando, se puede cargar haciendo puente con otro auto pero se volvera a agotar. Se recomienda comprar una nueva' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 48);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 49,'Es posible que el sistema tenga un fusible quemado, deberias cambiar esta pieza o todo el termostato completo' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 49);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 50,'Se recomienda cambiar la valvula, si el problema persiste llevar a un taller' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 50);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 51,'Se recomienda cambiar la pieza inmediatamente sino podria afectar al paso de combustible no quemado a traves del sistema de escape' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 51);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 52,'Para evitar incidentes cambiar urgente' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 52);
Insert into drivedoctor.diagnostico(idDiagnostico, descripcion ) SELECT 53,'Podria ser un problema de piston de freno, el material de friccion o las pastillas de freno lo recomendable seria que lo vea un mecanico' WHERE NOT EXISTS ( SELECT 1 FROM drivedoctor.diagnostico WHERE idDiagnostico = 53);


